src/Entity/Resultat.php
<?php

namespace App\Entity;

use App\Repository\ResultatRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Table;

/**
 * @ORM\Entity(repositoryClass=ResultatRepository::class)
 * @Table(name="resultats")
 */
class Resultat
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="resultats")
     */
    private $User;

    /**
     * @ORM\ManyToOne(targetEntity=Answer::class, inversedBy="resultats")
     */
    private $Answer;

    /**
     * @ORM\ManyToOne(targetEntity=Question::class, inversedBy="resultats")
     */
    private $Question;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getAnswer(): ?Answer
    {
        return $this->Answer;
    }

    public function setAnswer(?Answer $Answer): self
    {
        $this->Answer = $Answer;

        return $this;
    }

    public function getQuestion(): ?Question
    {
        return $this->Question;
    }

    public function setQuestion(?Question $Question): self
    {
        $this->Question = $Question;

        return $this;
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <link rel="icon" type="image/png" href="{{ asset('img/favicon.png') }}" />
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        <link href="{{ asset('css/style.css') }}" rel="stylesheet"/>
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}
        <script src="{{ asset('js/script.js') }}"></script>
        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/footer.html.twig
<footer>
    <div class="footer-containt">
        <p>Les P'ti sondages</p>
        <p>Erick Poix - LP DIM - Avril-Mai 2021</p>
        <a href="https://github.com/pepito5962/poll">Lien git</a>
        <a href="#">Mentions légales</a>
        <a href="#">Condition d'utilisation</a> 
    </div>
</footer>

templates/menu.html.twig
<nav>
    <div class="logo">
        <a href=" {{ path('app_home') }}"><img class="logo" src=" {{ asset('img/LogoSVG.svg') }}"/></a>
    </div>
    <ul class="nav">
        <li>
            <a href="{{ path('app_home') }}">Home</a>
        </li>
        {% if app.user %}
            <li>
                <a href="{{ path('app_create_sondage') }}">Créer un sondage</a>
            </li>
        {% endif %}
        {% if app.user %}
            <li>
                <a href="{{ path('app_user_area') }}">Mon espace perso</a>
            </li>
        {% endif %}
        {% if is_granted('ROLE_ADMIN') %}
            <li>
                <a href="{{ path('app_user_admin') }}">Administration</a>
            </li>
        {% endif %}
        <li>
            {% if app.user %}
                <a href="{{ path('app_logout') }}">Déconnexion</a>
            {% else %}
                <a href="{{ path('app_login') }}">Connexion</a>
            {% endif %} 
        </li>
        {% if not app.user %}
            <li>
                <a href="{{ path('app_register') }}">S'inscrire</a>
            </li>
        {% endif %}
    </ul>
</nav>